require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - Gemfile
    - Rakefile
    - 'bin/**/*'
    - 'config/puma.rb'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/initializers/devise.rb'

Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
RSpec/VariableName:
  IgnoredPatterns:
    - 'Authorization'
RSpec/MultipleExpectations:
  Max: 2