require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - Gemfile
    - Rakefile
    - 'bin/**/*'
    - 'config/puma.rb'