version: '3.8'
services:
  db:
    image: mysql:8
    command: ['--sql_mode=TRADITIONAL', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--authentication_policy=mysql_native_password', '--mysql-native-password=ON']
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3308:3306